In [3]:
import numpy as np
import pandas as pd

Array Creation And Manipulation


In [4]:
#Q1.1: Create a 4x4 identity matrix using np.eye()
import numpy as np
identity_matrix=np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [5]:
#Q1.2: Create an array of 8 zeros using np.zeros()
array_zeros = np.zeros(8)
print(array_zeros)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
#Q1.3: Create an array of 6 ones using np.ones()
array_ones =np.ones(6)
print(array_ones)

[1. 1. 1. 1. 1. 1.]


In [7]:
#Q1.4: Create an array with values from 0 to 15 using np.arange()
range_array =np.arange(16)
print(range_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [8]:
#Q1.5: Create an array with 8 evenly spaced values from 0 to 100 using np.linspace()
linspace_array=np.linspace(0,100,8)
print(linspace_array)

[  0.          14.28571429  28.57142857  42.85714286  57.14285714
  71.42857143  85.71428571 100.        ]


Array Attributes And Information

In [9]:
import numpy as np
#[Customer_ID,Account_Balance,Credit_Score,Transaction_Count,Years_Active]
banking_data = np.array([[ 1, 25000, 300, 1200, 10],
    [2, 12000, 450, 150, 5],
    [3, 28000, 380, 46, 8],
    [4, 41000, 500, 160, 18],
    [5, 35000, 420, 400, 12],
    [6, 27000, 360, 30, 9],
    [7, 39000, 480, 700, 18],
    [8, 30000, 400, 250, 14],
    [9, 45000, 420, 800, 20],
    [10, 23000, 410, 45, 9]])

print(banking_data)

[[    1 25000   300  1200    10]
 [    2 12000   450   150     5]
 [    3 28000   380    46     8]
 [    4 41000   500   160    18]
 [    5 35000   420   400    12]
 [    6 27000   360    30     9]
 [    7 39000   480   700    18]
 [    8 30000   400   250    14]
 [    9 45000   420   800    20]
 [   10 23000   410    45     9]]


In [10]:
#Q2.1: What is the shape of the banking_data array?
print(f"shape: {banking_data.shape}")

shape: (10, 5)


In [11]:
#Q2.2: What is the data type of the banking_data array?
print(f" data type: {banking_data.dtype}")

 data type: int64


In [12]:
#Q2.3: What is the size (total number of elements) of the banking_data array?
print(f"sie: {banking_data.size}")

sie: 50


In [13]:
#Q2.4: What is the number of dimensions of the banking_data array?
print(f"dim: {banking_data.ndim}")

dim: 2


In [14]:
#Q2.5: What is the memory size of the banking_data array in bytes?
print(f"bytes: {banking_data.nbytes}")

bytes: 400


Indexing And Slicing

In [15]:
import pandas as pd
#Q3.1: Extract the first row of banking_data
first_row = banking_data[0]
print(first_row)

[    1 25000   300  1200    10]


In [16]:
#Q3.2: Extract the last row of banking_data
last_row = banking_data[-1]
print(last_row)

[   10 23000   410    45     9]


In [17]:
#Q3.3: Extract the Account_Balance column (column index 1)
column_index=banking_data[:,1]
print(column_index)

[25000 12000 28000 41000 35000 27000 39000 30000 45000 23000]


In [18]:
#Q3.4: Extract the first 4 rows and first 3 columns
subset=banking_data[:3, :4]
print(subset)

[[    1 25000   300  1200]
 [    2 12000   450   150]
 [    3 28000   380    46]]


In [19]:
#Q3.5: Extract rows 3 to 7 (inclusive)
row_3_to_7=banking_data[3:7]
print(row_3_to_7)

[[    4 41000   500   160    18]
 [    5 35000   420   400    12]
 [    6 27000   360    30     9]
 [    7 39000   480   700    18]]


Mathematical Operation

In [20]:
#Q4.1: Calculate the sum of all account balances
total_balance=np.sum(banking_data[:,1])
print(total_balance)
                     

305000


In [21]:
#Q4.2: Calculate the mean account 
mean_account=np.mean(banking_data[:,1])
print(f"mean account :{mean_account}")


mean account :30500.0


In [22]:
#Q4.3: Calculate the standard deviation of account balances
std_balance=np.std(banking_data[:,1])
print(f" standard deviation of account :{std_balance}")

 standard deviation of account :9276.313923105448


In [23]:
#Q4.4: Calculate the variance of account balances
var_balance=np.var(banking_data[:,1])
print(f"variance of account :{var_balance}")

variance of account :86050000.0


In [24]:
#Q4.5: Calculate the median account balance
med_account=np.median(banking_data[:,1])
print(f"median account :{med_account}")

median account :29000.0


Statistical Functions

In [25]:
#Q5.1: Find the minimum and maximum account balances
min_balance= np.min(banking_data[:,1])
max_balance=np.max(banking_data[:,1])
print(f"minimum : {min_balance}")
print(f"maximum : {max_balance}")

minimum : 12000
maximum : 45000


In [26]:
#Q5.2: Find the minimum and maximum credit scores
min_scores=np.min(banking_data[:,2])
max_scores=np.max(banking_data[:,2])
print(f" minimum credits :{min_scores}")
print(f" maximum credits :{max_scores}")

 minimum credits :300
 maximum credits :500


In [27]:
#Q5.3: Calculate the percentile values for account balances (25th, 50th, 75th)
percentile = np.percentile(banking_data[:,1],[25,50,75])
print(f"+25th percentile : {percentile[0]}")
print(f"+50th percentile : {percentile[1]}")
print(f"+75th percentile : {percentile[2]}")

+25th percentile : 25500.0
+50th percentile : 29000.0
+75th percentile : 38000.0


In [28]:
#Q5.4: Calculate the correlation between account balance and credit score
correlation = np.corrcoef(banking_data[:,1],banking_data[:,3])[0,1]
print(f"correlation :{correlation}")

correlation :0.31433420336741874


In [29]:
#Q5.5: Calculate the covariance between account balance and credit score
covariance = np.cov(banking_data[:,1],banking_data[:,3])[0,1]
print(f"covariance :{covariance}")

covariance :1219166.6666666665


Array Reshaping And Manipulation

In [30]:
#Q6.1: Reshape the banking_data to 5 rows × 10 columns
reshaped_5x10=banking_data.reshape(5,10)
print(reshaped_5x10)
                                

[[    1 25000   300  1200    10     2 12000   450   150     5]
 [    3 28000   380    46     8     4 41000   500   160    18]
 [    5 35000   420   400    12     6 27000   360    30     9]
 [    7 39000   480   700    18     8 30000   400   250    14]
 [    9 45000   420   800    20    10 23000   410    45     9]]


In [31]:
#Q6.2: Flatten the banking_data to a 1D array
flattened = banking_data.flatten()
print(flattened)

[    1 25000   300  1200    10     2 12000   450   150     5     3 28000
   380    46     8     4 41000   500   160    18     5 35000   420   400
    12     6 27000   360    30     9     7 39000   480   700    18     8
 30000   400   250    14     9 45000   420   800    20    10 23000   410
    45     9]


In [32]:
#Q6.3: Transpose the banking_data
transposed = banking_data.transpose()
print(transposed)

[[    1     2     3     4     5     6     7     8     9    10]
 [25000 12000 28000 41000 35000 27000 39000 30000 45000 23000]
 [  300   450   380   500   420   360   480   400   420   410]
 [ 1200   150    46   160   400    30   700   250   800    45]
 [   10     5     8    18    12     9    18    14    20     9]]


In [33]:
#Q6.4: Split the banking_data into 2 equal parts vertically
split_vertical=np.vsplit (banking_data,2)
print(f"first part:{split_vertical[0]}")
print(f"second part:{split_vertical[1]}")

first part:[[    1 25000   300  1200    10]
 [    2 12000   450   150     5]
 [    3 28000   380    46     8]
 [    4 41000   500   160    18]
 [    5 35000   420   400    12]]
second part:[[    6 27000   360    30     9]
 [    7 39000   480   700    18]
 [    8 30000   400   250    14]
 [    9 45000   420   800    20]
 [   10 23000   410    45     9]]


In [34]:
#Q6.5: Split the banking_data into 2 equal parts horizontally
split_horizontal=np.hsplit(banking_data,2.5)
print(f"first_part:{split_horizontal[0]}")
print(f"second_part:{split_horizontal[1]}")

first_part:[[    1 25000   300]
 [    2 12000   450]
 [    3 28000   380]
 [    4 41000   500]
 [    5 35000   420]
 [    6 27000   360]
 [    7 39000   480]
 [    8 30000   400]
 [    9 45000   420]
 [   10 23000   410]]
second_part:[[1200   10]
 [ 150    5]
 [  46    8]
 [ 160   18]
 [ 400   12]
 [  30    9]
 [ 700   18]
 [ 250   14]
 [ 800   20]
 [  45    9]]


Logical operations and Filtering

In [35]:
#Q7.1: Find customers with account balance greater than $100,000
high_balance_customers = banking_data[:, 1] > 100,000
print(high_balance_customers)

(array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True]), 0)


In [36]:
#Q7.2: Find customers with credit score greater than 800
banking_data[:,2]>800

array([False, False, False, False, False, False, False, False, False,
       False])

In [37]:
#Q7.3: Find customers with transaction count greater than 50 AND credit score less than 750
banking_data[(banking_data[:, 3] > 50) & (banking_data[:, 2] < 750)]

array([[    1, 25000,   300,  1200,    10],
       [    2, 12000,   450,   150,     5],
       [    4, 41000,   500,   160,    18],
       [    5, 35000,   420,   400,    12],
       [    7, 39000,   480,   700,    18],
       [    8, 30000,   400,   250,    14],
       [    9, 45000,   420,   800,    20]])

In [38]:
#Q7.4: Count how many customers have account balance between $10,000 and $100,000
data = np.sum((banking_data[:,1] >= 10000) & (banking_data[:,1] <= 100000))
print(data)

10


In [39]:
#Q7.5: Find the index of the customer with the highest credit score
customer = np.argmax(banking_data[:, 2])+1
print(customer)

4


Sorting and Searching

In [40]:
#Q8.1: Sort the banking_data by account balance (ascending)
sorted_by_account=banking_data[banking_data[:,1].argsort()]
sorted_by_account

array([[    2, 12000,   450,   150,     5],
       [   10, 23000,   410,    45,     9],
       [    1, 25000,   300,  1200,    10],
       [    6, 27000,   360,    30,     9],
       [    3, 28000,   380,    46,     8],
       [    8, 30000,   400,   250,    14],
       [    5, 35000,   420,   400,    12],
       [    7, 39000,   480,   700,    18],
       [    4, 41000,   500,   160,    18],
       [    9, 45000,   420,   800,    20]])

In [41]:
#Q8.2: Sort the banking_data by credit score (descending)
data = banking_data[np.argsort(banking_data[:,3])[::-1]]
print(data)

[[    1 25000   300  1200    10]
 [    9 45000   420   800    20]
 [    7 39000   480   700    18]
 [    5 35000   420   400    12]
 [    8 30000   400   250    14]
 [    4 41000   500   160    18]
 [    2 12000   450   150     5]
 [    3 28000   380    46     8]
 [   10 23000   410    45     9]
 [    6 27000   360    30     9]]


In [42]:
#Q8.3: Find the indices that would sort the array by years active
active_indices= np.argsort(banking_data[:,4])
print(active_indices)

[1 2 5 9 0 4 7 3 6 8]


In [43]:
#Q8.4: Find the customer with the second highest account balance
second_highest_account = np.argsort(banking_data[:,1])[-2]
second_highest_account = banking_data[second_highest_account]
print(f"Customer ID: {int(second_highest_account[0])}, Account Balance: {int(second_highest_account[1])}")

Customer ID: 4, Account Balance: 41000


In [44]:
#Q8.5: Find the customer with the lowest transaction count
lowest_transaction = np.argmin(banking_data[:, 3])
lowest_transaction = banking_data[lowest_transaction]
print(f"Customer ID: {int(lowest_transaction [0])}, Transaction Count: {int(lowest_transaction [3])}")

Customer ID: 6, Transaction Count: 30


Mathematical Functions

In [45]:
#Q9.1: Calculate the absolute values of all elements
absolute_values = np.abs(banking_data)
print(absolute_values)

[[    1 25000   300  1200    10]
 [    2 12000   450   150     5]
 [    3 28000   380    46     8]
 [    4 41000   500   160    18]
 [    5 35000   420   400    12]
 [    6 27000   360    30     9]
 [    7 39000   480   700    18]
 [    8 30000   400   250    14]
 [    9 45000   420   800    20]
 [   10 23000   410    45     9]]


In [46]:
#Q9.2: Calculate the square root of all account balances
sqrt_account= np.sqrt(banking_data[:,2])
print(sqrt_account)

[17.32050808 21.21320344 19.49358869 22.36067977 20.49390153 18.97366596
 21.9089023  20.         20.49390153 20.24845673]


In [47]:
#Q9.3: Calculate the square of all credit scores
credit_scores=np.square(banking_data[:,2])
print(credit_scores)

[ 90000 202500 144400 250000 176400 129600 230400 160000 176400 168100]


In [48]:
#Q9.4: Calculate the exponential of all transaction counts
import numpy as np
banking_data = np.array([
    [ 1, 25000, 300, 1200, 10],
    [2, 12000, 450, 150, 5],
    [3, 28000, 380, 46, 8],
    [4, 41000, 500, 160, 18],
    [5, 35000, 420, 400, 12],
    [6, 27000, 360, 30, 9],
    [7, 39000, 480, 700, 18],
    [8, 30000, 400, 250, 14],
    [9, 45000, 420, 800, 20],
    [10, 23000, 410, 45, 9]])

print(banking_data)
np.exp(banking_data[:, 3])

[[    1 25000   300  1200    10]
 [    2 12000   450   150     5]
 [    3 28000   380    46     8]
 [    4 41000   500   160    18]
 [    5 35000   420   400    12]
 [    6 27000   360    30     9]
 [    7 39000   480   700    18]
 [    8 30000   400   250    14]
 [    9 45000   420   800    20]
 [   10 23000   410    45     9]]


C:\Users\dell\AppData\Local\Temp\ipykernel_14020\2203053695.py:16: RuntimeWarning: overflow encountered in exp
  np.exp(banking_data[:, 3])


array([            inf, 1.39370958e+065, 9.49611942e+019, 3.06984964e+069,
       5.22146969e+173, 1.06864746e+013, 1.01423205e+304, 3.74645461e+108,
                   inf, 3.49342711e+019])

In [49]:
#Q9.5: Calculate the natural logarithm of all account balances
logarithm= np.log(banking_data[:,1])
print(logarithm)

[10.1266311   9.39266193 10.23995979 10.62132735 10.46310334 10.20359214
 10.57131693 10.30895266 10.71441777 10.04324949]


Advanced Operations

In [50]:
#Q10.1: Calculate the cumulative sum of account balances
cummulative=np.sum(banking_data[:,1])
print(cummulative)

305000


In [51]:
#Q10.2: Calculate the cumulative product of transaction counts
cumprod_transaction=np.cumprod(banking_data[:,3])
print(cumprod_transaction)

[                1200               180000              8280000
           1324800000         529920000000       15897600000000
    11128320000000000  2782080000000000000 -6392032918855745536
  7506423830844276736]


Q10.3: Calculate the difference between consecutive account balances

diff_account = np.diff(banking_data[:, 1]) print(diff_account)

In [52]:
#Q10.4: Calculate the gradient of account balances
gradient_account= np.gradient(banking_data[:,1])
print(gradient_account)

[-13000.   1500.  14500.   3500.  -7000.   2000.   1500.   3000.  -3500.
 -22000.]


In [53]:
#Q10.5: Calculate the histogram of account balances with 5 bins
hist_account ,bin_edges=np.histogram(banking_data[:,1],bins=5)
print(f"histogram : {hist_account}")
print(f"bin_edges : {bin_edges}")

histogram : [1 2 3 1 3]
bin_edges : [12000. 18600. 25200. 31800. 38400. 45000.]


Random Numbers and Simulation

In [54]:
#Q11.1: Generate 6 random integers between 1 and 1000
random_int = np.random.randint(1,1001,6)
print(random_int)

[148 265 104  53 448 222]


In [55]:
#Q11.2: Generate 6 random floats between 0 and 1
random_floats = np.random.random(6)
print(random_floats)

[0.87901803 0.21835113 0.91966679 0.69375127 0.71565528 0.82254715]


In [56]:
#Q11.3: Generate 6 random numbers from normal distribution (mean=700, std=100) normal_random = np.random.normal(700,100,6) print(normal_random)
normal_random = np.random.normal(700,100,6)
print(normal_random)


[624.54694465 519.11924421 935.15712845 754.90627323 701.64070332
 606.2291375 ]


In [57]:
#Q11.4: Shuffle the banking_data rows randomly
shuffled_data = banking_data.copy()
np.random.shuffle(shuffled_data)
print(shuffled_data)

[[   10 23000   410    45     9]
 [    9 45000   420   800    20]
 [    6 27000   360    30     9]
 [    5 35000   420   400    12]
 [    2 12000   450   150     5]
 [    7 39000   480   700    18]
 [    3 28000   380    46     8]
 [    4 41000   500   160    18]
 [    8 30000   400   250    14]
 [    1 25000   300  1200    10]]


In [58]:
#Q11.5: Set random seed to 123 and generate 4 random numbers
np.random.seed(123)
seeded_random = np.random.random(4)
print(seeded_random)

[0.69646919 0.28613933 0.22685145 0.55131477]


Linear Algebra Operations

In [59]:
#Q12.1: Calculate the dot product of account balance and credit score columns
dot_product=np.dot(banking_data[:,1],banking_data[:,2])
print(f"dot product : {dot_product}")

dot product : 127510000


In [60]:
#Q12.2: Calculate the cross product of first two rows
cross_product=np.cross(banking_data[0,:3],banking_data[1,:3])
print(cross_product)

[7650000     150  -38000]


In [61]:
#Q12.3: Calculate the norm (magnitude) of the account balance column
account_norm =np.linalg.norm(banking_data[:,1])
print(account_norm)

100811.70566953026


In [62]:
#Q12.4: Create a 3x3 matrix and calculate its determinant
matrix_3x3 = np.array([ 
    [2, 5, 3],
    [1, -2, 9],
    [3, 6, 2]
])
determinant = np.linalg.det(matrix_3x3)
print(f"Matrix :\n{matrix_3x3}")
print(f"determinant : {determinant}")

Matrix :
[[ 2  5  3]
 [ 1 -2  9]
 [ 3  6  2]]
determinant : 44.99999999999999


In [63]:
#Q12.5: Calculate the inverse of the 3x3 matrix
inverse_matrix = np.linalg.inv(matrix_3x3)
print(inverse_matrix)

[[-1.28888889  0.17777778  1.13333333]
 [ 0.55555556 -0.11111111 -0.33333333]
 [ 0.26666667  0.06666667 -0.2       ]]


String Operations

In [64]:
#Q13.1: Convert all customer IDs to strings
customer_IDs_str = banking_data[:, 0].astype(str)  #stringarrayusing.astype()
print(customer_IDs_str)

['1' '2' '3' '4' '5' '6' '7' '8' '9' '10']


In [65]:
#Q13.2: Check if any customer ID contains '100'
customer_100 = np.char.find(customer_IDs_str, '100') >= 0
print(customer_100)

[False False False False False False False False False False]


In [66]:
#Q13.3: Convert all customer IDs to uppercase (if they were strings)
customer_IDs_upper = np.char.upper(customer_IDs_str)
print(customer_IDs_upper)

['1' '2' '3' '4' '5' '6' '7' '8' '9' '10']


In [67]:
#Q13.4: Count the length of each customer ID string
Id_length = np.char.str_len(customer_IDs_str)
print(Id_length)

[1 1 1 1 1 1 1 1 1 2]


In [68]:
#Q13.5: Replace '100' with 'CUST' in customer IDs
replaced_Ids = np.char.replace(customer_IDs_str, '100', 'CUST')
print(replaced_Ids)

['1' '2' '3' '4' '5' '6' '7' '8' '9' '10']


Date and Time Operations

In [69]:
 #Q14.1: Convert years active to months
years_active=banking_data[:,4]*12
print(years_active)

[120  60  96 216 144 108 216 168 240 108]


In [70]:
#Q14.2: Calculate the average years active
average_years=np.mean(banking_data[:,4])
print(f"average years :{average_years}")

average years :12.3


In [75]:
#Q14.3: Find customers who have been active for more than 5 years
long_active = banking_data[banking_data[:,4] > 5]
print(long_active)

[[    1 25000   300  1200    10]
 [    3 28000   380    46     8]
 [    4 41000   500   160    18]
 [    5 35000   420   400    12]
 [    6 27000   360    30     9]
 [    7 39000   480   700    18]
 [    8 30000   400   250    14]
 [    9 45000   420   800    20]
 [   10 23000   410    45     9]]
