Array Creation And Manipulation


In [2]:
#Q1.1: Create a 4x4 identity matrix using np.eye()
import numpy as np
identity_matrix=np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [3]:
#Q1.2: Create an array of 8 zeros using np.zeros()
array_zeros = np.zeros(8)
print(array_zeros)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
#Q1.3: Create an array of 6 ones using np.ones()
array_ones =np.ones(6)
print(array_ones)

[1. 1. 1. 1. 1. 1.]


In [9]:
#Q1.4: Create an array with values from 0 to 15 using np.arange()
range_array =np.arange(16)
print(range_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [10]:
#Q1.5: Create an array with 8 evenly spaced values from 0 to 100 using np.linspace()
linspace_array=np.linspace(0,100,8)
print(linspace_array)

[  0.          14.28571429  28.57142857  42.85714286  57.14285714
  71.42857143  85.71428571 100.        ]


Array Attributes And Information

In [11]:
import numpy as np
#[Customer_ID,Account_Balance,Credit_Score,Transaction_Count,Years_Active]
banking_data = np.array([[ 1, 25000, 300, 1200, 10],
    [2, 12000, 450, 150, 5],
    [3, 28000, 380, 46, 8],
    [4, 41000, 500, 160, 18],
    [5, 35000, 420, 400, 12],
    [6, 27000, 360, 30, 9],
    [7, 39000, 480, 700, 18],
    [8, 30000, 400, 250, 14],
    [9, 45000, 420, 800, 20],
    [10, 23000, 410, 45, 9]])

print(banking_data)

[[    1 25000   300  1200    10]
 [    2 12000   450   150     5]
 [    3 28000   380    46     8]
 [    4 41000   500   160    18]
 [    5 35000   420   400    12]
 [    6 27000   360    30     9]
 [    7 39000   480   700    18]
 [    8 30000   400   250    14]
 [    9 45000   420   800    20]
 [   10 23000   410    45     9]]


In [14]:
#Q2.1: What is the shape of the banking_data array?
print(f"shape: {banking_data.shape}")

shape: (10, 5)


In [15]:
#Q2.2: What is the data type of the banking_data array?
print(f" data type: {banking_data.dtype}")

 data type: int64


In [16]:
#Q2.3: What is the size (total number of elements) of the banking_data array?
print(f"sie: {banking_data.size}")

sie: 50


In [ ]:
#Q2.4: What is the number of dimensions of the banking_data array?
print(f"dim: {banking_data.ndim}")

ndim: 2


In [19]:
#Q2.5: What is the memory size of the banking_data array in bytes?
print(f"bytes: {banking_data.nbytes}")

bytes: 400


Indexing And Slicing